# Практическое задание

## Урок 3. TensorFlow

1. Попробуйте улучшить работу нейронной сети (разобранную на уроке) обучавшейся на датасет Fashion-MNIST.
2. Опишите в комментарии к уроку - какого результата вы добились от нейросети? Что помогло вам улучшить ее точность?
3. Поработайте с документацией TensorFlow 2. Попробуйте найти полезные команды TensorFlow, неразобранные на уроке
4.  *Попробуйте обучить нейронную сеть на TensorFlow 2 на датасете imdb_reviews.

---

## Задание 1 и 2

### 1. Импорт библиотек и модулей 

In [1]:
import pandas as pd

import tensorflow as tf
from tensorflow import keras

#Helper libraries
import numpy as np

# визуализация 
import matplotlib.pyplot as plt

# датасет Fashion MNIST
from keras.datasets import fashion_mnist

# для создания комбинация числа нейронов сркытых слоев
from itertools import combinations, combinations_with_replacement

# создание модели нейронной сети 
from keras.layers import Dense       # Полносвязный линейный слой
from keras.models import Sequential  # Класс последовательности 

from keras.utils import to_categorical

print(tf.__version__)

2.13.0


In [2]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [3]:
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()


print(train_images.shape, test_images.shape)
print(train_labels.shape)

(60000, 28, 28) (10000, 28, 28)
(60000,)


### 2. Нормировка

In [4]:
train_images = train_images / 255.0
test_images = test_images / 255.0

### 3. Reshape

In [5]:
train_images = train_images.reshape((-1, 784))
test_images = test_images.reshape((-1, 784))

train_images.shape, test_images.shape

((60000, 784), (10000, 784))

In [6]:
v = np.array([x for x in range(100)])
v.reshape(1,100)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [7]:
v = train_images[0].copy()
v[v > 0] = 1
v = v.astype(np.int16)

In [8]:
class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

In [9]:
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

test_labels[:5]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]], dtype=float32)

### 4.Анализ датасета

#### 4.1. Тренировочная подвыборка 

In [10]:
print(train_images.shape)
print(len(train_labels))
print(train_labels)

(60000, 784)
60000
[[0. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


Вывод: train_images содержит 60 000 изображений, train_labels содержит 60 000 меток 

#### 4.2. Тестовая подвыборка

In [11]:
print(test_images.shape)
print(len(test_labels))
print(test_labels)

(10000, 784)
10000
[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


Вывод: test_images содержит 10 000 изображений, test_labels содержит 10 000 меток 

### 5. Создание модели

#### 5.1. Определение числа слоев и количества нейронов в слоях

In [12]:
# число нейронов скрытого слоя
neuron_numb = [60, 90, 120, 150]

In [13]:
# список числа слоев 
layers_numb = [2, 3] 

In [14]:
# создадим комбинации числа нейронов скрытого слоя из списка neuron_numb для разного количества слоев 

comb_neuron_numb_dict_some_layes = {}

n = 1
for el in layers_numb:
    comb_neuron_numb_layes = combinations_with_replacement(neuron_numb, el)
    for i in list(comb_neuron_numb_layes):
#         print(i)
        comb_neuron_numb_dict_some_layes[str(i)] = i
        
        
# print(comb_neuron_numb_dict_some_layes)

# for k in comb_neuron_numb_dict_some_layes:
#     print(len(comb_neuron_numb_dict_some_layes.get(k)))

In [15]:
# список для сохранения результатов
list_metris_total_neural_network_some_layers = []

# список наименований столбцов
list_cols = ['neuron_numb_for_layers', 'layers_numb', 'accuracy']

In [16]:
# функция для получения нейронной сети с различным количеством слоев 

def learning_neural_network_some_layers(train_images, train_labels, test_images, test_labels, layers_numb, **kwargs):    
    model_some_layers = Sequential()

    l_nn = kwargs.get(k)
    model_some_layers.add(Dense(l_nn[0], input_shape=(28 * 28,), activation='relu')) # input-слой + первый скрытый слой
           
    for i in range(1, n+1): # для кажого слоя в диапазоне от 2-х до ... заданного
        model_some_layers.add(Dense(l_nn[n], activation='relu')) # остальные скрытые слои

   
    model_some_layers.add(Dense(10, activation='sigmoid')) # output-слой

    # компиляция модели 
    model_some_layers.compile(loss='categorical_crossentropy', 
                              optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), 
                              metrics=['accuracy'])
    
    history = model_some_layers.fit(train_images, train_labels,
                    epochs=5,
                    batch_size=250, 
                    verbose=0,
#                     validation_data=(test_images, test_labels)
                    validation_split=0.2) # валидация 20% от train
    
    best_metrics_model_some_layers = round(float(history.history['accuracy'][4])*100, 2) # значений accuracy последней эпохи
#     print(best_metrics_model_some_layers)
    list_total = []
    list_total.append(l_nn) # количество нейронов по слоям 
    list_total.append(layers_numb) # количество слоев нейронной сети 
    list_total.append(best_metrics_model_some_layers) # значение accuracy
                                          
    list_metris_total_neural_network_some_layers.append(list_total)
    
# model.summary()

In [17]:
%%time

for k in comb_neuron_numb_dict_some_layes:
    learning_neural_network_some_layers(train_images=train_images, 
                              train_labels=train_labels, 
                              test_images=test_images, 
                              test_labels=test_labels, 
                              layers_numb=int(len(comb_neuron_numb_dict_some_layes.get(k))),  
                              **comb_neuron_numb_dict_some_layes)
    
# CPU times: total: 3min 35s
# Wall time: 1min 27s

CPU times: total: 3min 35s
Wall time: 1min 27s


In [18]:
# сформируем датасет из списков, включающих значения о количестве нейронов в каждом слое и метрику - accuracy 
data_neural_network_some_layers = pd.DataFrame(list_metris_total_neural_network_some_layers, columns=list_cols)
# отсортируем полученные данные по столбцу точность нейронной сети(accuracy)
data_neural_network_some_layers.sort_values(by=list_cols[2], ascending=False).head(3)

neuron_numb_for_layers  layers_numb  accuracy
9              (150, 150)            2     88.56
8              (120, 150)            2     88.46
29        (150, 150, 150)            3     88.27

Вывод: лучшая модель нейронной сети была получена при количестве скрытых слоев - 2 по 150 нейронов в каждом скрытом слое

### 6. Компиляция лучшей модели 

In [19]:
%%time

model_some_layers = Sequential()

model_some_layers.add(Dense(150, input_shape=(28 * 28,), activation='relu')) # input-слой + первый скрытый слой
model_some_layers.add(Dense(150, activation='relu'))
model_some_layers.add(Dense(10, activation='sigmoid')) # output-слой

# компиляция модели 
model_some_layers.compile(loss='categorical_crossentropy', 
                          optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), 
                          metrics=['accuracy'])

history = model_some_layers.fit(train_images, train_labels,
                epochs=5,
                batch_size=250,
                verbose=0,
                validation_split=0.2
                )

best_metrics_model_some_layers = round(float(history.history['accuracy'][4])*100, 2) # значений accuracy последней эпохи
print(best_metrics_model_some_layers)

88.71
CPU times: total: 14.3 s
Wall time: 4.29 s


In [20]:
model_some_layers.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss='categorical_crossentropy', metrics=['accuracy'])

In [21]:
test_loss, test_acc = model_some_layers.evaluate(test_images,  test_labels, batch_size=250)

print('\nTest accuracy:', test_acc*100)

40/40 [==============================] - 0s 1ms/step - loss: 0.3558 - accuracy: 0.8726

Test accuracy: 87.26000189781189


In [22]:
model_some_layers.summary()

Model: "sequential_30"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_90 (Dense)            (None, 150)               117750    
                                                                 
 dense_91 (Dense)            (None, 150)               22650     
                                                                 
 dense_92 (Dense)            (None, 10)                1510      
                                                                 
Total params: 141910 (554.34 KB)
Trainable params: 141910 (554.34 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


### 7. Предсказания нейросети и  проверка предсказаний

In [23]:
probability_model = tf.keras.Sequential([model_some_layers,
                                         tf.keras.layers.Softmax()])

In [24]:
predictions = probability_model.predict(test_images)

313/313 [==============================] - 0s 768us/step


In [25]:
predictions[0]

array([0.06693191, 0.06657659, 0.06828964, 0.06692111, 0.06635953,
       0.17164865, 0.06848565, 0.17300393, 0.07196634, 0.17981662],
      dtype=float32)

In [26]:
np.argmax(predictions[0])

9

In [27]:
test_labels[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32)

предсказание соответсвует индексу тестовых меток - 9

In [28]:
np.argmax(predictions[20])

2

In [29]:
test_labels[20]

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

предсказание соответсвует индексу тестовых меток - 2

Вывод: Улучшение точности представленной нейронной сети было получено за счет подбора количества скрытых слоев и количества нейронов в каждом скрытом слое, когда метрика accuracy достигала максимального значения при заданных праметрах 

---

## Задание 3

## Полезные команды TensorFlow, неразобранные на уроке

1. Проверка работы GPU

In [30]:
# возвращает доступные GPU 

x = tf.random.uniform([0, 0])

print(tf.config.experimental.list_physical_devices('GPU'))
print(x.device.endswith)

[]
<built-in method endswith of str object at 0x000001D1BF331890>


2. Получение словаря, описывающего среду сборки

In [31]:
tf.sysconfig.get_build_info()

OrderedDict([('is_cuda_build', False),
             ('is_rocm_build', False),
             ('is_tensorrt_build', False),
             ('msvcp_dll_names', 'msvcp140.dll,msvcp140_1.dll')])

3. Возвращает флаги компиляции для компиляции с помощью TensorFlow.

In [ ]:
print(tf.sysconfig.get_compile_flags())

4. Генерация набора классов 

In [33]:
num_true = 10 # Количество целевых классов на обучающий пример.
num_sampled = 10 # Количество возможных позиций 

tf.random.all_candidate_sampler(
    train_labels, num_true, num_sampled, unique=True, seed=None, name=None
)

AllCandidateSampler(sampled_candidates=<tf.Tensor: shape=(10,), dtype=int64, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)>, true_expected_count=<tf.Tensor: shape=(60000, 10), dtype=float32, numpy=
array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], dtype=float32)>, sampled_expected_count=<tf.Tensor: shape=(10,), dtype=float32, numpy=array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)>)

5. Подсчет повторов целочисленных значений в тензоре

In [34]:
data = np.array([[10, 20, 30, 20], [11, 101, 11, 10001]], dtype=np.int64)
output = tf.sparse.bincount(data, axis=-1)
print(output)

SparseTensor(indices=tf.Tensor(
[[    0    10]
 [    0    20]
 [    0    30]
 [    1    11]
 [    1   101]
 [    1 10001]], shape=(6, 2), dtype=int64), values=tf.Tensor([1 2 1 2 1 1], shape=(6,), dtype=int64), dense_shape=tf.Tensor([    2 10002], shape=(2,), dtype=int64))
